/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aguabendita.view;

import aguabendita.bo.Fac_Detalle_BO;
import aguabendita.entity.Fac_Detalle;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class formFacDetalle extends javax.swing.JFrame {

    /**
     * Creates new form formFacDetalle
     */
    private Fac_Detalle_BO fbo = new Fac_Detalle_BO();
    
    public formFacDetalle() {
        initComponents();
        listarFacturaDetalle();
        idMax();
        setTitle("Formulario Factura Detalle");
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    
    
    public void idMax(){ 
       int i = fbo.getMaxID();
        System.out.println(i);
       txtIdFactura.setText(i+"");
    }
    
    public void listarFacturaDetalle(){
        fbo.listarFacturaDetalle(tbFac_Detalle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFkPromocion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdFactura = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtFkEncabezado = new javax.swing.JTextField();
        txtFkBebida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFac_Detalle = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btmEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("FK Promoción:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 20));

        txtFkPromocion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFkPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFkPromocionActionPerformed(evt);
            }
        });
        txtFkPromocion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFkPromocionKeyTyped(evt);
            }
        });
        jPanel1.add(txtFkPromocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Formulario de factura - detalle");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID Detalle fac:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("FK Encabezado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("FK Bebida:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 20));

        txtIdFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdFacturaActionPerformed(evt);
            }
        });
        txtIdFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdFacturaKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, -1));

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, -1));

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 140, -1));

        txtFkEncabezado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFkEncabezado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFkEncabezadoActionPerformed(evt);
            }
        });
        txtFkEncabezado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFkEncabezadoKeyTyped(evt);
            }
        });
        jPanel1.add(txtFkEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, -1));

        txtFkBebida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFkBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFkBebidaActionPerformed(evt);
            }
        });
        txtFkBebida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFkBebidaKeyTyped(evt);
            }
        });
        jPanel1.add(txtFkBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, -1));

        tbFac_Detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbFac_Detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFac_DetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFac_Detalle);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 380, 180));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 90, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        btmEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btmEliminar.setText("Eliminar");
        btmEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btmEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFkPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFkPromocionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFkPromocionActionPerformed

    private void txtIdFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFacturaActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtFkEncabezadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFkEncabezadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFkEncabezadoActionPerformed

    private void txtFkBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFkBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFkBebidaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (camposVacios()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else if (Integer.parseInt(txtIdFactura.getText()) < fbo.getMaxID()) {
            JOptionPane.showMessageDialog(null, "El registro con codigo "+txtIdFactura.getText()+" ya existe");
        }else{
            Fac_Detalle fac = new Fac_Detalle();
            fac.setIdFac_Detalle(Integer.parseInt(txtIdFactura.getText()));
            fac.setCantidad(Integer.parseInt(txtCantidad.getText()));
            fac.setTotal(Double.parseDouble(txtTotal.getText()));
            fac.setFk_Encabezado(Integer.parseInt(txtFkEncabezado.getText()));
            fac.setFk_bebida(Integer.parseInt(txtFkBebida.getText()));
            fac.setFk_promocion(Integer.parseInt(txtFkPromocion.getText()));
            String mensaje = fbo.agregarFacturaDetalle(fac);
            limpiarCampos();
            listarFacturaDetalle();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (camposVacios()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }else if (Integer.parseInt(txtIdFactura.getText()) > fbo.getMaxID()) {
            JOptionPane.showMessageDialog(null, "El registro con codigo "+txtIdFactura.getText()+" no existe");
        }else{
            Fac_Detalle fac = new Fac_Detalle();
            fac.setIdFac_Detalle(Integer.parseInt(txtIdFactura.getText()));
            fac.setCantidad(Integer.parseInt(txtCantidad.getText()));
            fac.setTotal(Double.parseDouble(txtTotal.getText()));
            fac.setFk_Encabezado(Integer.parseInt(txtFkEncabezado.getText()));
            fac.setFk_bebida(Integer.parseInt(txtFkBebida.getText()));
            fac.setFk_promocion(Integer.parseInt(txtFkPromocion.getText()));
            String mensaje = fbo.modificarFacturaDetalle(fac);
            limpiarCampos();
            listarFacturaDetalle();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btmEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmEliminarActionPerformed
            if (txtIdFactura.getText().isEmpty() || Integer.parseInt(txtIdFactura.getText()) > fbo.getMaxID()) {
            JOptionPane.showMessageDialog(null, "El registro con codigo "+txtIdFactura.getText()+" no existe");
             }else{
                String mensaje = fbo.eliminarFacturaDetalle(Integer.parseInt(txtIdFactura.getText()));
                limpiarCampos();
                listarFacturaDetalle();
             }
    }//GEN-LAST:event_btmEliminarActionPerformed

    private void tbFac_DetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFac_DetalleMouseClicked
        int seleccion = tbFac_Detalle.rowAtPoint(evt.getPoint());
        
        txtFkEncabezado.setText(tbFac_Detalle.getValueAt(seleccion, 0)+"");
        txtIdFactura.setText(tbFac_Detalle.getValueAt(seleccion, 1)+"");
        txtFkBebida.setText(tbFac_Detalle.getValueAt(seleccion, 2)+"");
        txtCantidad.setText(tbFac_Detalle.getValueAt(seleccion, 3)+"");
        txtFkPromocion.setText(tbFac_Detalle.getValueAt(seleccion, 4)+"");
        txtTotal.setText(tbFac_Detalle.getValueAt(seleccion, 5)+"");
        
    }//GEN-LAST:event_tbFac_DetalleMouseClicked

    private void txtFkEncabezadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFkEncabezadoKeyTyped
        char c = evt.getKeyChar();
        if (c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txtFkEncabezadoKeyTyped

    private void txtIdFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdFacturaKeyTyped
        char c = evt.getKeyChar();
        if (c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txtIdFacturaKeyTyped

    private void txtFkBebidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFkBebidaKeyTyped
        char c = evt.getKeyChar();
        if (c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txtFkBebidaKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if (c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtFkPromocionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFkPromocionKeyTyped
        char c = evt.getKeyChar();
        if (c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txtFkPromocionKeyTyped

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped
        char c = evt.getKeyChar();
        if (c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txtTotalKeyTyped

    public void limpiarCampos(){
        txtCantidad.setText("");
        txtFkBebida.setText("");
        txtFkEncabezado.setText("");
        txtFkPromocion.setText("");
        txtIdFactura.setText("");
        txtTotal.setText("");
        idMax();
    }
    
    public boolean camposVacios(){
        if (txtCantidad.getText().isEmpty()
                ||txtFkBebida.getText().isEmpty()
                ||txtFkEncabezado.getText().isEmpty()
                ||txtFkPromocion.getText().isEmpty()
                ||txtIdFactura.getText().isEmpty()
                ||txtTotal.getText().isEmpty()) {
            return true;
        }else{
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formFacDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formFacDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formFacDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formFacDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formFacDetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmEliminar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbFac_Detalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFkBebida;
    private javax.swing.JTextField txtFkEncabezado;
    private javax.swing.JTextField txtFkPromocion;
    private javax.swing.JTextField txtIdFactura;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
